worker: node bot.js
worker2: node bot2.js
worker3: node bot3.js
worker4: node bot4.js
worker5: node bot5.js
worker6: node bot6.js
worker7: node bot7.js
worker8: node bot8.js
worker9: node bot9.js
worker10: node bot10.js
